### ISSUE TITLE
Provide ability to watch graph

### ISSUE THREAD

**Issue by chaos-adept** [chaos-adept/monkey-tournament#15]

**Comment by vicnbt** [comment]
![image](https://cloud.githubusercontent.com/assets/2864268/23054656/54cbc4be-f4f2-11e6-8e95-786abacbd01a.png)

**Comment by chaos-adept** [comment]
а что есть цифры? это количество за день?

**Comment by vicnbt** [comment]
да

**Comment by vicnbt** [comment]
вообще наверное в таких графиках смысла нет, наверное стоит добавить графики для истории

**Comment by chaos-adept** [comment]
сейчас идет подпиливание под еластик #16 если инвестигейшен пройдет успешно то можно будет потенциально какие то из коробки кибаны получать

https://yandex.ru/images/search?text=kibana%20grapth&parent-reqid=1487705835928935-1177617629165193537005884-sas1-1243

**Comment by chaos-adept** [comment]
kibana currently cover this functionality
